apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "clickhouse-cluster"
spec:
  configuration:
    clusters:
      - name: "cluster1"
  defaults:
    templates:
      podTemplate: clickhouse-default
      volumeClaimTemplate: clickhouse-storage
  templates:
    podTemplates:
      - name: clickhouse-default
        spec:
          nodeSelector:
            clickhouse-node: "true"
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server:latest
    volumeClaimTemplates:
      - name: clickhouse-storage
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
