apiVersion: v1
kind: Namespace
metadata:
  name: cronjobs
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: insert-cronjob
  namespace: cronjobs
spec:
  schedule: "*/15 * * * *"
  timeZone: "Asia/Tokyo"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: fetch
              image: sirogami/scripts:latest
              imagePullPolicy: Always
              args: ["insert"]
              env:
                - name: CLICKHOUSE_DSN
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-dsn
                      key: dsn
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-problem-cronjob
  namespace: cronjobs
spec:
  schedule: "0 3 * * *"
  timeZone: "Asia/Tokyo"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: fetch
              image: sirogami/scripts:latest
              imagePullPolicy: Always
              args: ["update_problems"]
              env:
                - name: CLICKHOUSE_DSN
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-dsn
                      key: dsn
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: complete-cronjob
  namespace: cronjobs
spec:
  schedule: "0 3 * * *"
  timeZone: "Asia/Tokyo"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: fetch
              image: sirogami/scripts:latest
              imagePullPolicy: Always
              args: ["complete"]
              env:
                - name: CLICKHOUSE_DSN
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-dsn
                      key: dsn
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-rating-cronjob
  namespace: cronjobs
spec:
  schedule: "0 0 * * *"
  timeZone: "Asia/Tokyo"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: fetch
              image: sirogami/scripts:latest
              imagePullPolicy: Always
              args: ["update_rating"]
              env:
                - name: CLICKHOUSE_DSN
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-dsn
                      key: dsn
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: insert-contest-cronjob
  namespace: cronjobs
spec:
  schedule: "0 1 * * *"
  timeZone: "Asia/Tokyo"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: fetch
              image: sirogami/scripts:latest
              imagePullPolicy: Always
              args: ["insert_contest"]
              env:
                - name: CLICKHOUSE_DSN
                  valueFrom:
                    secretKeyRef:
                      name: clickhouse-dsn
                      key: dsn
          restartPolicy: Never
---
# submission テーブルを全体をリプレイスするやつ、後回し
#apiVersion: batch/v1
#kind: CronJob
#metadata:
#  name: insert-all-cronjob
#  namespace: cronjobs
#spec:
#  schedule: "0 4 * * 0"
#  jobTemplate:
#    spec:
#      ttlSecondsAfterFinished: 3600
#      template:
#        spec:
#          containers:
#            - name: fetch
#              image: sirogami/scripts:latest
#              imagePullPolicy: Always
#              args: ["insert_all"]
#          restartPolicy: OnFailure
