---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: clickhouse-dsn
  namespace: cronjobs
spec:
  encryptedData:
    dsn: AgCewxbFHeXKs7mvYt2iji4U3ZPMXRmoR5RNbYl8Q2OsuofIFb6aks7GgiIX70ZWYsa28Rx8DOW+JTEFO8xNm1GtutiqESIe5mzuIJENnAen9ETOfqZJp6nHFiiED6U3mBe7DilqBJVdR9qQfXy0vIeLL+aZEeXT3VM3D/Jw1Qpf6Cn6offQyCztnmE5BIbnToDjoZLuO01s1ss3XObR3/j4FGbDU/r8h47pfivFx7SQyRNVVZd6irmXBsdqssHmmfQa37h++5F5SvCFT8q1y1KuFp5CRrCW1j/SYMehXALuScVSrMqJS/0P4IS8oT/sG5VW6w7QqMKUZV6gytqRtEwSCWjF3thrncKCmtUDc9SeuFfa+SbXNLytPHH79Uvh1ONMh3nCQUHuUipmOlfplrO1TCnJ5gUIwwUe+F8OigRay0ccyAFXGAgBvqKJoYyCDF8qTPOuZQZYAY/ZJL11hPgh1wXTdGWg3HPzsur/kXwM9CquSNfukyo0k1wpkmOuF8oU3lk6DgcPCD+xjKO+I5xutZwjRonElFPf7WJVWHNP0GxiBnsNSAuqp8x3IIBWMZc4fELqV3xqDVk0qB2JNhwdDDF7phvw3I0el83GaeZYHxZ8vRXq6xhE8FZa6ogq+42ylA2tZrEJ8j4GqVw0Hc0wxXTQ8CPBo0hdYFYdvbEdrBZI1cycbUxl9rDrB0fEeyeFT8uZIM9oL3eQUC53VQbV51oGSIeAHrISNVpw6QtxdQfmkmvkUJhl2yhO2cXCvcsTPJfuWKX2S4LfWA4pRgYiBGU0ZS7qckXVURYjbEDWZJ14Y59sB2yfxECPGTw+eR0jrnW3o2YJsmxFjw==
  template:
    metadata:
      creationTimestamp: null
      name: clickhouse-dsn
      namespace: cronjobs
