name: Deploy to k3s

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ acepc1 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy manifests
        run: |
          kubectl apply -R -f k3s
