name: Deploy to k3s

on:
  push:
    branches: [ main ]
    paths:
      - 'k3s/**'
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: [ self-hosted, acepc1 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy manifests
        run: |
          kubectl --kubeconfig=/home/sirogami/.kube/config apply -R -f k3s
